### ISSUE TITLE
Quelle der Zahlen

### ISSUE THREAD

**Issue by apriljunge** [stefanw/ifg-vis#3]
Da die Prozentzahlen wie in #2 schon angemerkt ist, zumindest für 2016 nicht stimmen können (124% beim BMF), wäre es praktisch zu wissen wie sich diese Zahlen zusammensetzen. Stammen die Daten aus der API von fragdenstaat?

**Comment by stefanw** [comment]
Die Zahlen kommen aus der [offiziellen IFG-Statistik des Bundes](https://www.bmi.bund.de/DE/themen/moderne-verwaltung/open-government/informationsfreiheitsgesetz/informationsfreiheitsgesetz-node.html). Die liegt leider nur bis 2017 vor. Leider hat sich bei der Berechnung der Statistik auf Bundesseite auch etwas geändert, weswegen die Prozente auch nicht mehr aufgehen.
